name: CI

on:
  push:
  pull_request:

jobs:
  wasm_test:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Install wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rust-src
          
      - uses: Swatinem/rust-cache@v2

      - name: Check native
        run: cargo check --all-targets